FROM golang:1.12-alpine AS build

RUN apk add --update make bash curl docker sudo git gcc

WORKDIR /install

COPY .travis/* ./

RUN chmod +x *.sh \
 && ./install_dep.sh \
 && ./install_operator_sdk.sh \
 && find . -type f ! -name '*.sh' -delete

RUN ln -s /go/src/github.com/edgelevel/lastpass-operator /workspace

RUN adduser -D -u 1001 dev

USER dev

WORKDIR /workspace

ENV GO111MODULE=on

RUN echo "make docker-build tag=latest" > /home/dev/.bash_history
